### ISSUE TITLE
Line ends are broken when template html is minimized for <script> tag

### ISSUE THREAD

**Issue by kuceram** [craigburke/angular-template-asset-pipeline#29]
Having following code:

```
<div>
   some content
</div>
<script type="text/ng-template" id="myTemplate.html">
   <div>
      test
   </div>
</script>
```

is compressed to:
`<div>some content</div><script type="text/ng-template" id="myTemplate.html">    n<div> n      test n n </div> n</script>`

I found some similar issues of the past...
https://github.com/craigburke/angular-template-asset-pipeline/issues/7
https://github.com/craigburke/angular-template-asset-pipeline/issues/11

**Comment by craigburke** [comment]
@kuceram you're using Windows, right? I think I know what the problem is here.

**Comment by craigburke** [comment]
This should be resolved in the latest version `2.3.0` feel free to reopen if I'm wrong.

**Comment by kuceram** [comment]
This is still an issue. I don't use windows (I have Mac) but I use editor config which sets the line ends to LF. Btw. I don't probably have rights for reopening this issue...

**Comment by craigburke** [comment]
@kuceram ok that's helpful. I'll take a look.

**Comment by craigburke** [comment]
@kuceram take a look at version 2.4.0 just released and take a look at the new preserveLineBreaks property it should address your issue.

**Comment by passionfruit18** [comment]
Have you pushed this to the grails plugin repository?
